// source: items/items.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.sizematch.protobuf.items.Dimension', null, global);
goog.exportSymbol('proto.sizematch.protobuf.items.Dimension.Name', null, global);
goog.exportSymbol('proto.sizematch.protobuf.items.Dimension.Unit', null, global);
goog.exportSymbol('proto.sizematch.protobuf.items.Item', null, global);
goog.exportSymbol('proto.sizematch.protobuf.items.Lang', null, global);
goog.exportSymbol('proto.sizematch.protobuf.items.NormalizedItem', null, global);
goog.exportSymbol('proto.sizematch.protobuf.items.Price', null, global);
goog.exportSymbol('proto.sizematch.protobuf.items.Price.Currency', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sizematch.protobuf.items.Item = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sizematch.protobuf.items.Item.repeatedFields_, null);
};
goog.inherits(proto.sizematch.protobuf.items.Item, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sizematch.protobuf.items.Item.displayName = 'proto.sizematch.protobuf.items.Item';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sizematch.protobuf.items.NormalizedItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.sizematch.protobuf.items.NormalizedItem.repeatedFields_, null);
};
goog.inherits(proto.sizematch.protobuf.items.NormalizedItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sizematch.protobuf.items.NormalizedItem.displayName = 'proto.sizematch.protobuf.items.NormalizedItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sizematch.protobuf.items.Dimension = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sizematch.protobuf.items.Dimension, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sizematch.protobuf.items.Dimension.displayName = 'proto.sizematch.protobuf.items.Dimension';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sizematch.protobuf.items.Price = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sizematch.protobuf.items.Price, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sizematch.protobuf.items.Price.displayName = 'proto.sizematch.protobuf.items.Price';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sizematch.protobuf.items.Item.repeatedFields_ = [4,7,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sizematch.protobuf.items.Item.prototype.toObject = function(opt_includeInstance) {
  return proto.sizematch.protobuf.items.Item.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sizematch.protobuf.items.Item} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.Item.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    source: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lang: jspb.Message.getFieldWithDefault(msg, 3, 0),
    urlsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    categoriesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    imageUrlsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    dimensionsMap: (f = msg.getDimensionsMap()) ? f.toObject(includeInstance, undefined) : [],
    price: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    priceCurrency: jspb.Message.getFieldWithDefault(msg, 11, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sizematch.protobuf.items.Item}
 */
proto.sizematch.protobuf.items.Item.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sizematch.protobuf.items.Item;
  return proto.sizematch.protobuf.items.Item.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sizematch.protobuf.items.Item} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sizematch.protobuf.items.Item}
 */
proto.sizematch.protobuf.items.Item.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 3:
      var value = /** @type {!proto.sizematch.protobuf.items.Lang} */ (reader.readEnum());
      msg.setLang(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addUrls(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addCategories(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addImageUrls(value);
      break;
    case 9:
      var value = msg.getDimensionsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    case 10:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPrice(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setPriceCurrency(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sizematch.protobuf.items.Item.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sizematch.protobuf.items.Item.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sizematch.protobuf.items.Item} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.Item.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLang();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getUrlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getImageUrlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getDimensionsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      10,
      f
    );
  }
  f = message.getPriceCurrency();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.sizematch.protobuf.items.Item.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string source = 2;
 * @return {string}
 */
proto.sizematch.protobuf.items.Item.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Lang lang = 3;
 * @return {!proto.sizematch.protobuf.items.Lang}
 */
proto.sizematch.protobuf.items.Item.prototype.getLang = function() {
  return /** @type {!proto.sizematch.protobuf.items.Lang} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sizematch.protobuf.items.Lang} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setLang = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * repeated string urls = 4;
 * @return {!Array<string>}
 */
proto.sizematch.protobuf.items.Item.prototype.getUrlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setUrlsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.addUrls = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.clearUrlsList = function() {
  return this.setUrlsList([]);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.sizematch.protobuf.items.Item.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.sizematch.protobuf.items.Item.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated string categories = 7;
 * @return {!Array<string>}
 */
proto.sizematch.protobuf.items.Item.prototype.getCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setCategoriesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.addCategories = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.clearCategoriesList = function() {
  return this.setCategoriesList([]);
};


/**
 * repeated string image_urls = 8;
 * @return {!Array<string>}
 */
proto.sizematch.protobuf.items.Item.prototype.getImageUrlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setImageUrlsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.addImageUrls = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.clearImageUrlsList = function() {
  return this.setImageUrlsList([]);
};


/**
 * map<string, string> dimensions = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.sizematch.protobuf.items.Item.prototype.getDimensionsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.clearDimensionsMap = function() {
  this.getDimensionsMap().clear();
  return this;};


/**
 * optional double price = 10;
 * @return {number}
 */
proto.sizematch.protobuf.items.Item.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional string price_currency = 11;
 * @return {string}
 */
proto.sizematch.protobuf.items.Item.prototype.getPriceCurrency = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setPriceCurrency = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string brand = 12;
 * @return {string}
 */
proto.sizematch.protobuf.items.Item.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.Item} returns this
 */
proto.sizematch.protobuf.items.Item.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.sizematch.protobuf.items.NormalizedItem.repeatedFields_ = [4,7,8,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.toObject = function(opt_includeInstance) {
  return proto.sizematch.protobuf.items.NormalizedItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sizematch.protobuf.items.NormalizedItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.NormalizedItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    source: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lang: jspb.Message.getFieldWithDefault(msg, 3, 0),
    urlsList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f,
    name: jspb.Message.getFieldWithDefault(msg, 5, ""),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    categoriesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    imageUrlsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    dimensionsList: jspb.Message.toObjectList(msg.getDimensionsList(),
    proto.sizematch.protobuf.items.Dimension.toObject, includeInstance),
    price: (f = msg.getPrice()) && proto.sizematch.protobuf.items.Price.toObject(includeInstance, f),
    brand: jspb.Message.getFieldWithDefault(msg, 11, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sizematch.protobuf.items.NormalizedItem}
 */
proto.sizematch.protobuf.items.NormalizedItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sizematch.protobuf.items.NormalizedItem;
  return proto.sizematch.protobuf.items.NormalizedItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sizematch.protobuf.items.NormalizedItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sizematch.protobuf.items.NormalizedItem}
 */
proto.sizematch.protobuf.items.NormalizedItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSource(value);
      break;
    case 3:
      var value = /** @type {!proto.sizematch.protobuf.items.Lang} */ (reader.readEnum());
      msg.setLang(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addUrls(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addCategories(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addImageUrls(value);
      break;
    case 9:
      var value = new proto.sizematch.protobuf.items.Dimension;
      reader.readMessage(value,proto.sizematch.protobuf.items.Dimension.deserializeBinaryFromReader);
      msg.addDimensions(value);
      break;
    case 10:
      var value = new proto.sizematch.protobuf.items.Price;
      reader.readMessage(value,proto.sizematch.protobuf.items.Price.deserializeBinaryFromReader);
      msg.setPrice(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sizematch.protobuf.items.NormalizedItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sizematch.protobuf.items.NormalizedItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.NormalizedItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSource();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLang();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getUrlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getImageUrlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getDimensionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      proto.sizematch.protobuf.items.Dimension.serializeBinaryToWriter
    );
  }
  f = message.getPrice();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.sizematch.protobuf.items.Price.serializeBinaryToWriter
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string source = 2;
 * @return {string}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getSource = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setSource = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Lang lang = 3;
 * @return {!proto.sizematch.protobuf.items.Lang}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getLang = function() {
  return /** @type {!proto.sizematch.protobuf.items.Lang} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sizematch.protobuf.items.Lang} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setLang = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * repeated string urls = 4;
 * @return {!Array<string>}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getUrlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setUrlsList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.addUrls = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.clearUrlsList = function() {
  return this.setUrlsList([]);
};


/**
 * optional string name = 5;
 * @return {string}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated string categories = 7;
 * @return {!Array<string>}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setCategoriesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.addCategories = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.clearCategoriesList = function() {
  return this.setCategoriesList([]);
};


/**
 * repeated string image_urls = 8;
 * @return {!Array<string>}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getImageUrlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setImageUrlsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.addImageUrls = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.clearImageUrlsList = function() {
  return this.setImageUrlsList([]);
};


/**
 * repeated Dimension dimensions = 9;
 * @return {!Array<!proto.sizematch.protobuf.items.Dimension>}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getDimensionsList = function() {
  return /** @type{!Array<!proto.sizematch.protobuf.items.Dimension>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.sizematch.protobuf.items.Dimension, 9));
};


/**
 * @param {!Array<!proto.sizematch.protobuf.items.Dimension>} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
*/
proto.sizematch.protobuf.items.NormalizedItem.prototype.setDimensionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.sizematch.protobuf.items.Dimension=} opt_value
 * @param {number=} opt_index
 * @return {!proto.sizematch.protobuf.items.Dimension}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.addDimensions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.sizematch.protobuf.items.Dimension, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.clearDimensionsList = function() {
  return this.setDimensionsList([]);
};


/**
 * optional Price price = 10;
 * @return {?proto.sizematch.protobuf.items.Price}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getPrice = function() {
  return /** @type{?proto.sizematch.protobuf.items.Price} */ (
    jspb.Message.getWrapperField(this, proto.sizematch.protobuf.items.Price, 10));
};


/**
 * @param {?proto.sizematch.protobuf.items.Price|undefined} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
*/
proto.sizematch.protobuf.items.NormalizedItem.prototype.setPrice = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.clearPrice = function() {
  return this.setPrice(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.hasPrice = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional string brand = 11;
 * @return {string}
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.sizematch.protobuf.items.NormalizedItem} returns this
 */
proto.sizematch.protobuf.items.NormalizedItem.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sizematch.protobuf.items.Dimension.prototype.toObject = function(opt_includeInstance) {
  return proto.sizematch.protobuf.items.Dimension.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sizematch.protobuf.items.Dimension} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.Dimension.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, 0),
    value: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    unit: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sizematch.protobuf.items.Dimension}
 */
proto.sizematch.protobuf.items.Dimension.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sizematch.protobuf.items.Dimension;
  return proto.sizematch.protobuf.items.Dimension.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sizematch.protobuf.items.Dimension} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sizematch.protobuf.items.Dimension}
 */
proto.sizematch.protobuf.items.Dimension.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.sizematch.protobuf.items.Dimension.Name} */ (reader.readEnum());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setValue(value);
      break;
    case 3:
      var value = /** @type {!proto.sizematch.protobuf.items.Dimension.Unit} */ (reader.readEnum());
      msg.setUnit(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sizematch.protobuf.items.Dimension.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sizematch.protobuf.items.Dimension.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sizematch.protobuf.items.Dimension} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.Dimension.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getUnit();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sizematch.protobuf.items.Dimension.Name = {
  HEIGHT: 0,
  WIDTH: 1,
  DEPTH: 2,
  WEIGHT: 3,
  LENGTH: 4,
  DIAMETER: 5,
  VOLUME: 6,
  THICKNESS: 7
};

/**
 * @enum {number}
 */
proto.sizematch.protobuf.items.Dimension.Unit = {
  MM: 0,
  CM: 1,
  M: 2,
  G: 3,
  KG: 4,
  MM2: 5,
  CM2: 6,
  M2: 7,
  MM3: 8,
  CM3: 9,
  M3: 10,
  L: 11,
  CL: 12,
  ML: 13
};

/**
 * optional Name name = 1;
 * @return {!proto.sizematch.protobuf.items.Dimension.Name}
 */
proto.sizematch.protobuf.items.Dimension.prototype.getName = function() {
  return /** @type {!proto.sizematch.protobuf.items.Dimension.Name} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.sizematch.protobuf.items.Dimension.Name} value
 * @return {!proto.sizematch.protobuf.items.Dimension} returns this
 */
proto.sizematch.protobuf.items.Dimension.prototype.setName = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional double value = 2;
 * @return {number}
 */
proto.sizematch.protobuf.items.Dimension.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sizematch.protobuf.items.Dimension} returns this
 */
proto.sizematch.protobuf.items.Dimension.prototype.setValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional Unit unit = 3;
 * @return {!proto.sizematch.protobuf.items.Dimension.Unit}
 */
proto.sizematch.protobuf.items.Dimension.prototype.getUnit = function() {
  return /** @type {!proto.sizematch.protobuf.items.Dimension.Unit} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.sizematch.protobuf.items.Dimension.Unit} value
 * @return {!proto.sizematch.protobuf.items.Dimension} returns this
 */
proto.sizematch.protobuf.items.Dimension.prototype.setUnit = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sizematch.protobuf.items.Price.prototype.toObject = function(opt_includeInstance) {
  return proto.sizematch.protobuf.items.Price.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sizematch.protobuf.items.Price} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.Price.toObject = function(includeInstance, msg) {
  var f, obj = {
    amount: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    currency: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sizematch.protobuf.items.Price}
 */
proto.sizematch.protobuf.items.Price.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sizematch.protobuf.items.Price;
  return proto.sizematch.protobuf.items.Price.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sizematch.protobuf.items.Price} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sizematch.protobuf.items.Price}
 */
proto.sizematch.protobuf.items.Price.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAmount(value);
      break;
    case 2:
      var value = /** @type {!proto.sizematch.protobuf.items.Price.Currency} */ (reader.readEnum());
      msg.setCurrency(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sizematch.protobuf.items.Price.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sizematch.protobuf.items.Price.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sizematch.protobuf.items.Price} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sizematch.protobuf.items.Price.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAmount();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getCurrency();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.sizematch.protobuf.items.Price.Currency = {
  EUR: 0,
  GBP: 1
};

/**
 * optional double amount = 1;
 * @return {number}
 */
proto.sizematch.protobuf.items.Price.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.sizematch.protobuf.items.Price} returns this
 */
proto.sizematch.protobuf.items.Price.prototype.setAmount = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional Currency currency = 2;
 * @return {!proto.sizematch.protobuf.items.Price.Currency}
 */
proto.sizematch.protobuf.items.Price.prototype.getCurrency = function() {
  return /** @type {!proto.sizematch.protobuf.items.Price.Currency} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.sizematch.protobuf.items.Price.Currency} value
 * @return {!proto.sizematch.protobuf.items.Price} returns this
 */
proto.sizematch.protobuf.items.Price.prototype.setCurrency = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * @enum {number}
 */
proto.sizematch.protobuf.items.Lang = {
  EN: 0,
  FR: 1
};

goog.object.extend(exports, proto.sizematch.protobuf.items);
